apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: dagster-deploy
  namespace: '1065304831367'
  selfLink: >-
    /apis/serving.knative.dev/v1/namespaces/1065304831367/services/dagster-deploy
  uid: 356b62d2-22f2-419c-a800-23c45abf4e2a
  resourceVersion: AAY2n9jB3WI
  generation: 13
  creationTimestamp: '2025-06-02T19:25:14.916641Z'
  labels:
    cloud.googleapis.com/location: us-east1
  annotations:
    serving.knative.dev/creator: rvernica@gmail.com
    serving.knative.dev/lastModifier: rvernica@gmail.com
    run.googleapis.com/client-name: cloud-console
    run.googleapis.com/operation-id: c0b9edbf-011e-4464-b078-641812e68213
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/invoker-iam-disabled: 'true'
    run.googleapis.com/urls: >-
      ["https://dagster-deploy-1065304831367.us-east1.run.app","https://dagster-deploy-2h2ikx6v4q-ue.a.run.app"]
spec:
  template:
    metadata:
      labels:
        client.knative.dev/nonce: c4f26938-9db1-4500-902a-20cd79041776
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '100'
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
        run.googleapis.com/container-dependencies: >-
          {"dagster-deploy-1":["dagster-university-1"],"dagster-deploy-2":["dagster-university-1"]}
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 1065304831367-compute@developer.gserviceaccount.com
      containers:
      - name: dagster-deploy-1
        image: >-
          us-east1-docker.pkg.dev/gen-lang-client-0795290170/github-container-registry/rvernica/dagster-deploy:latest
        command:
        - dagster-webserver
        args:
        - '-h'
        - 0.0.0.0
        - '-p'
        - '3000'
        - '-w'
        - workspace.yaml
        ports:
        - name: http1
          containerPort: 3000
        env:
        - name: DAGSTER_CODE_UNI
          value: localhost
        - name: DAGSTER_PG_USERNAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_username_dagaster
        - name: DAGSTER_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_password_dagster
        - name: DAGSTER_PG_HOST
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_host
        - name: DAGSTER_PG_DB
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_dbname_dagster
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 240
          periodSeconds: 240
          failureThreshold: 1
          tcpSocket:
            port: 3000
      - name: dagster-university-1
        image: >-
          us-east1-docker.pkg.dev/gen-lang-client-0795290170/github-container-registry/rvernica/dagster-university:latest
        env:
        - name: DAGSTER_CURRENT_IMAGE
          value: dagster-university
        - name: DUCKDB_DATABASE
          value: data/staging/data.duckdb
        - name: DAGSTER_PG_USERNAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_username_dagaster
        - name: DAGSTER_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_password_dagster
        - name: DAGSTER_PG_HOST
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_host
        - name: DAGSTER_PG_DB
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_dbname_dagster
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
        startupProbe:
          timeoutSeconds: 1
          periodSeconds: 10
          failureThreshold: 3
          grpc:
            port: 4000
            service: DagsterApi
      - name: dagster-deploy-2
        image: >-
          us-east1-docker.pkg.dev/gen-lang-client-0795290170/github-container-registry/rvernica/dagster-deploy:latest
        command:
        - dagster-daemon
        args:
        - run
        env:
        - name: DAGSTER_CODE_UNI
          value: localhost
        - name: DAGSTER_PG_USERNAME
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_username_dagaster
        - name: DAGSTER_PG_PASSWORD
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_password_dagster
        - name: DAGSTER_PG_HOST
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_host
        - name: DAGSTER_PG_DB
          valueFrom:
            secretKeyRef:
              key: latest
              name: postgres_dbname_dagster
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
